//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMDIRandomizer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMDIRandomizer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Back_32x32 {
            get {
                object obj = ResourceManager.GetObject("Back_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thre randomization process was cancelled..
        /// </summary>
        internal static string CancelledMessage {
            get {
                return ResourceManager.GetString("CancelledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing....
        /// </summary>
        internal static string ConfirmClosingCaption {
            get {
                return ResourceManager.GetString("ConfirmClosingCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A randomization process is currently running.
        ///
        ///Are you shure you want to stop it and close the application?.
        /// </summary>
        internal static string ConfirmClosingMessage {
            get {
                return ResourceManager.GetString("ConfirmClosingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Copy_32x32 {
            get {
                object obj = ResourceManager.GetObject("Copy_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casual.
        /// </summary>
        internal static string Difficulty_Casual {
            get {
                return ResourceManager.GetString("Difficulty.Casual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Randomization.
        /// </summary>
        internal static string Difficulty_Full {
            get {
                return ResourceManager.GetString("Difficulty.Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard.
        /// </summary>
        internal static string Difficulty_Hard {
            get {
                return ResourceManager.GetString("Difficulty.Hard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string Difficulty_Normal {
            get {
                return ResourceManager.GetString("Difficulty.Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Mode.
        /// </summary>
        internal static string Difficulty_Open {
            get {
                return ResourceManager.GetString("Difficulty.Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tournament.
        /// </summary>
        internal static string Difficulty_Tournament {
            get {
                return ResourceManager.GetString("Difficulty.Tournament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; started sucessfully!.
        /// </summary>
        internal static string EmulatorStartedMessage {
            get {
                return ResourceManager.GetString("EmulatorStartedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected problem ocurred while trying to start the emulator..
        /// </summary>
        internal static string EmulatorStartingErrorMessage {
            get {
                return ResourceManager.GetString("EmulatorStartingErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting &quot;{0}&quot; with the last randomized ROM file....
        /// </summary>
        internal static string EmulatorStartingMessage {
            get {
                return ResourceManager.GetString("EmulatorStartingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Error_32x32 {
            get {
                object obj = ResourceManager.GetObject("Error_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Error_64x64 {
            get {
                object obj = ResourceManager.GetObject("Error_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while processing..
        /// </summary>
        internal static string ErrorCaption {
            get {
                return ResourceManager.GetString("ErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error ocurred while trying to randomize the selected ROM file.
        ///
        ///Make shure you are using a valid vanilla (unheadered) Super Metroid ROM file and that you have permission to read from and write to the ROM source file location..
        /// </summary>
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a valid file path..
        /// </summary>
        internal static string FilePathWarning {
            get {
                return ResourceManager.GetString("FilePathWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Foward_32x32 {
            get {
                object obj = ResourceManager.GetObject("Foward_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your randomized file(s) can be found in the same folder containing the original ROM file..
        /// </summary>
        internal static string GenerateROMLocation {
            get {
                return ResourceManager.GetString("GenerateROMLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application has encontered a error..
        /// </summary>
        internal static string GenericErrorMessage {
            get {
                return ResourceManager.GetString("GenericErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Info_32x32 {
            get {
                object obj = ResourceManager.GetObject("Info_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using the default parameters instead..
        /// </summary>
        internal static string LoadingDefaultMessage {
            get {
                return ResourceManager.GetString("LoadingDefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading ROM File....
        /// </summary>
        internal static string LoadingRomMessage {
            get {
                return ResourceManager.GetString("LoadingRomMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ROM file was loaded sucessfully..
        /// </summary>
        internal static string LoadingRomMessageSucess {
            get {
                return ResourceManager.GetString("LoadingRomMessageSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An problem ocurred while loading your last randomization parameters..
        /// </summary>
        internal static string LoadingSettingsErrorMessage {
            get {
                return ResourceManager.GetString("LoadingSettingsErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log file {0} ({1} file(s) in total).
        /// </summary>
        internal static string LogErrorCountLabel {
            get {
                return ResourceManager.GetString("LogErrorCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomizing ROM with the seed {0} [{1} / {2}]....
        /// </summary>
        internal static string RandomizingMessage {
            get {
                return ResourceManager.GetString("RandomizingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomized file {0} saved sucessfully..
        /// </summary>
        internal static string RandomizingMessageSucess {
            get {
                return ResourceManager.GetString("RandomizingMessageSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error ocurred while trying to randomize de selected ROM file..
        /// </summary>
        internal static string ShortErrorMessage {
            get {
                return ResourceManager.GetString("ShortErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SMBackgroud {
            get {
                object obj = ResourceManager.GetObject("SMBackgroud", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomization completed!.
        /// </summary>
        internal static string SucessfullRandomizationMessage {
            get {
                return ResourceManager.GetString("SucessfullRandomizationMessage", resourceCulture);
            }
        }
    }
}
